CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_HWINFO=y

CONFIG_BT=y
CONFIG_BT_L2CAP_TX_BUF_COUNT=5
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_BROADCASTER=y

CONFIG_BT_CTLR_DUP_FILTER_LEN=0
CONFIG_BT_CTLR_LE_ENC=n
CONFIG_BT_CTLR_LE_PING=n
CONFIG_BT_DATA_LEN_UPDATE=n
CONFIG_BT_PHY_UPDATE=n
CONFIG_BT_CTLR_MIN_USED_CHAN=n
CONFIG_BT_CTLR_PRIVACY=n
CONFIG_BT_CTLR_CHAN_SEL_2=n

CONFIG_BT_MESH=y
CONFIG_BT_MESH_MODEL_EXTENSIONS=y
CONFIG_BT_MESH_RELAY=y
CONFIG_BT_MESH_FRIEND=y
CONFIG_BT_MESH_PB_GATT=y
CONFIG_BT_MESH_PB_ADV=y
CONFIG_BT_MESH_GATT_PROXY=y

CONFIG_BT_MESH_SUBNET_COUNT=2
CONFIG_BT_MESH_APP_KEY_COUNT=2
CONFIG_BT_MESH_MODEL_GROUP_COUNT=2
CONFIG_BT_MESH_LABEL_COUNT=3

CONFIG_BT_EXT_ADV=n
CONFIG_BT_MESH_ADV_STACK_SIZE=3000
CONFIG_BT_MESH_SETTINGS_WORKQ_STACK_SIZE=1500

CONFIG_LOG=y

CONFIG_THREAD_NAME=y
CONFIG_SEGGER_SYSTEMVIEW=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_TRACING=y
CONFIG_TRACING_BACKEND_RAM=y
CONFIG_TRACING_BUFFER_SIZE=8192

CONFIG_TRACING_CONDVAR=n
CONFIG_TRACING_FIFO=n            # 禁用FIFO队列跟踪
CONFIG_TRACING_LIFO=n            # 禁用LIFO队列跟踪
CONFIG_TRACING_STACK=n
CONFIG_TRACING_MESSAGE_QUEUE=n   # 禁用队列事件跟踪
CONFIG_TRACING_MAILBOX=n
CONFIG_TRACING_PIPE=n
CONFIG_TRACING_HEAP=n
CONFIG_TRACING_MEMORY_SLAB=n
CONFIG_TRACING_TIMER=n
CONFIG_TRACING_MUTEX=n
CONFIG_TRACING_QUEUE=n
CONFIG_TRACING_SYSCALL=n
CONFIG_TRACING_EVENT=n
CONFIG_TRACING_POLLING=n
CONFIG_TRACING_PM=n

# CONFIG_BT_MESH_ADV_BUF_COUNT=10

# CONFIG_BT_BUF_CMD_TX_COUNT=10
# CONFIG_BT_HCI_CORE_LOG_LEVEL_DBG=y

# CONFIG_DEBUG_COREDUMP=y
# CONFIG_LOG_MODE_MINIMAL=y

# CONFIG_SHELL=y
# CONFIG_BT_MESH_SHELL=y
# CONFIG_BT_MESH_SHELL_CDB=y

# CONFIG_BT_HCI_ACL_FLOW_CONTROL=n